2021-12-02 17:51:34,672 INFO    MainThread:1688836 [wandb_setup.py:_flush():69] setting env: {}
2021-12-02 17:51:34,673 INFO    MainThread:1688836 [wandb_setup.py:_flush():69] setting login settings: {}
2021-12-02 17:51:34,673 INFO    MainThread:1688836 [wandb_init.py:_log_setup():357] Logging user logs to /home/lts5-ts/Documents/ahmed/bmai_ahmed/wandb/run-20211202_175134-223zvdeb/logs/debug.log
2021-12-02 17:51:34,673 INFO    MainThread:1688836 [wandb_init.py:_log_setup():358] Logging internal logs to /home/lts5-ts/Documents/ahmed/bmai_ahmed/wandb/run-20211202_175134-223zvdeb/logs/debug-internal.log
2021-12-02 17:51:34,673 INFO    MainThread:1688836 [wandb_init.py:init():390] calling init triggers
2021-12-02 17:51:34,673 INFO    MainThread:1688836 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-12-02 17:51:34,673 INFO    MainThread:1688836 [wandb_init.py:init():435] starting backend
2021-12-02 17:51:34,674 INFO    MainThread:1688836 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-02 17:51:34,691 INFO    MainThread:1688836 [backend.py:ensure_launched():135] starting backend process...
2021-12-02 17:51:34,697 INFO    MainThread:1688836 [backend.py:ensure_launched():139] started backend process with pid: 1688844
2021-12-02 17:51:34,698 INFO    MainThread:1688836 [wandb_init.py:init():440] backend started and connected
2021-12-02 17:51:34,698 INFO    MainThread:1688836 [wandb_init.py:init():499] updated telemetry
2021-12-02 17:51:34,699 INFO    MainThread:1688836 [wandb_init.py:init():522] communicating current version
2021-12-02 17:51:35,130 INFO    MainThread:1688836 [wandb_init.py:init():527] got version response upgrade_message: "wandb version 0.12.7 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-12-02 17:51:35,130 INFO    MainThread:1688836 [wandb_init.py:init():535] communicating run to backend with 30 second timeout
2021-12-02 17:51:35,363 INFO    MainThread:1688836 [wandb_init.py:init():562] starting run threads in backend
2021-12-02 17:51:36,629 INFO    MainThread:1688836 [wandb_run.py:_console_start():1651] atexit reg
2021-12-02 17:51:36,630 INFO    MainThread:1688836 [wandb_run.py:_redirect():1525] redirect: SettingsConsole.REDIRECT
2021-12-02 17:51:36,630 INFO    MainThread:1688836 [wandb_run.py:_redirect():1530] Redirecting console.
2021-12-02 17:51:36,631 INFO    MainThread:1688836 [wandb_run.py:_redirect():1586] Redirects installed.
2021-12-02 17:51:36,631 INFO    MainThread:1688836 [wandb_init.py:init():587] run started, returning control to user process
2021-12-02 17:51:36,632 INFO    MainThread:1688836 [wandb_run.py:_atexit_cleanup():1621] got exitcode: 2
2021-12-02 17:51:36,632 INFO    MainThread:1688836 [wandb_run.py:_restore():1593] restore
2021-12-02 17:51:39,142 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 1089
}

2021-12-02 17:51:39,252 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 1089
}

2021-12-02 17:51:39,431 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 1089
}

2021-12-02 17:51:40,395 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 1649
}

2021-12-02 17:51:40,498 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 7983
}

2021-12-02 17:51:40,599 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 7983
}

2021-12-02 17:51:40,702 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7983
  total_bytes: 7983
}

2021-12-02 17:51:40,805 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7983
  total_bytes: 7983
}

2021-12-02 17:51:40,907 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7983
  total_bytes: 7983
}

2021-12-02 17:51:41,010 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7983
  total_bytes: 7983
}

2021-12-02 17:51:41,113 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7983
  total_bytes: 7983
}

2021-12-02 17:51:41,328 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7983
  total_bytes: 7983
}

2021-12-02 17:51:41,733 INFO    MainThread:1688836 [wandb_run.py:_wait_for_finish():1746] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7983
  total_bytes: 7983
}
local_info {
}

2021-12-02 17:51:42,809 INFO    MainThread:1688836 [wandb_run.py:_append_files():2009] logging synced files
