
About to train for 10 epochs
Traceback (most recent call last):
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/demo_bmai.py", line 53, in <module>
    main(args)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/demo_bmai.py", line 44, in main
    results,mean_training_loss = trainer.train(args.epochs)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/trainer_bmai_2.py", line 123, in train
    results = pd.DataFrame(columns=['mean_height_rel_error','mean_weight_rel_error'])
NameError: name 'pd' is not defined